<?php
/**
 * @file
 * Code for the Pages feature.
 */

include_once 'tree_pages.features.inc';

/**
 * Implements hook_og_features_registry()
 */
function tree_pages_og_features_registry() {
  $registry = array();
  $feature = new stdClass();
  $feature->id = 'tree_pages';
  $feature->name = t('Pages');
  $feature->description = t('Provide static pages to your space.');
  $feature->components = array(
    'node' => array(
      'tree_page',
    ),
  );
  $registry[$feature->id] = $feature;
  return $registry;
}

