<?php
/**
 * @file
 * Code for the News feature.
 */

include_once 'tree_news.features.inc';

/**
 * Implements hook_og_features_registry()
 */
function tree_news_og_features_registry() {
  $registry = array();
  $feature = new stdClass();
  $feature->id = 'tree_news';
  $feature->name = t('News');
  $feature->description = t('Provide news articles to your space.');
  $feature->components = array(
    'node' => array(
      'tree_news',
    ),
  );
  $registry[$feature->id] = $feature;
  return $registry;
}

/**
 * Implements hook_og_features_toggle($entity, $entity_id, $entity_type, $features)
 */
function tree_news_og_features_toggle($entity, $entity_id, $entity_type, $features) {
  if (isset($features['tree_news'])) {
    $mlid = og_menu_single_get_link_mlid('node', $entity_id);
    if (empty($features['tree_news'])) {
      menu_link_delete(NULL, 'node/'.$entity_id.'/news');
    }
    else {
      // See if menu link already exists
      $menu_link = menu_link_get_preferred('node/'.$entity_id.'/news', OG_MENU_SINGLE_MENU_NAME);
      if (empty($menu_link)) {
        $menu_link = array(
          'link_path' => 'node/'.$entity_id.'/news',
          'link_title' => 'News',
          'menu_name' => OG_MENU_SINGLE_MENU_NAME,
          'weight' => 6,
          'plid' => $mlid,
        );
        menu_link_save($menu_link);
      }
    }
  }

}

